"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 2.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '66d2muz%n5e0lxhhde&c^as%d&sr*vh14xwc8!+m!fdv#xc3hs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

private_key = {
    "type": "service_account",
    "project_id": "codeutsava-48425",
    "private_key_id": "2ba34be8e9da315a9a135ca714225838f636801b",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCnwV5hI6MfopTv\nI8mZkWz4nNwCkORTkKIXZVqLQRpY8BpnWUhRJrZYHEHoteSIYy4skSwkI0picGML\ncosUhbugiy6Ubk5QYtnAmUhGesM0Pl6GLJKcgERYjW82wR4Wxwsfvnvx07B0JbZA\ng1oq/QI+Rw0DitoZ8Ogd04gYowR5F7kcqRTyvquFjWSMDy3EaV12QPdqvEouI5up\n5NDKcFfY1l8YUS9/BZkGQZHS4N7h0RUJN8oBOvDCieFO4siQ5dxoNthclZlOsYRl\nktNGZQA7U+YNXT3C+LQ63QYCtwnzW0FcIGrJ+TGQoZL/Rs/l4K6LUl13MQ37jzgZ\nl/cQYr1PAgMBAAECggEARFDiH4sExkBOiKi5U9m+V+yBSGY7JbDT4dU7r1Qe57M3\n/XiFk87BGVbAnIVegRBq4GlqYXkhtL7yBtppuzzO8Q1dNcNKD0CCTwXdQh6CWkc/\n9UI3npY5vxox/Uld+IasiAvpq8y6okItW05irPkGLdh/ez7TnRbXYDYhyW6xxqHy\ntraeh8bvto5DCXuRqIVPTFbw1IixFfjSAzIxPFXLp/2aKhGrnJoS8dF5Slf29kee\nVBR94wrwO18bpjsFsu0Rq9ca1KvURdsbmqt57s4DEZngn3+zm4XgBFjfdlJFE1Xo\nmV+Kie05JpWy+jwZCd0BdnHVRwOjjZ509tLH8al68QKBgQDWKNZyNd65cjFnTjNM\nGTf9fYZGMVJwA9cend9rxZuNapgJ/89psTrEvd447Di00lw88ayHgITdLog0eGaz\nbTHPFnva0pzl/GrDYUfVSum+XbtXyYi/qMSPq1n7+Y52nuvnKpYI/cWk3ovgNue0\nOzUDFA49ST8KeFKs1GM9NBRzdwKBgQDIh6G+O/HW6oHkGA0Yt1Yr4YiZ9Y4OUeod\nB/2QPDcFrDSCPRoTtQxMexFpYbqdxohgimPsZnDFmiHux4PJHTFOy341kVnZM/2r\nGewLiHltKt6L0L4VsQ++5x3JyXODhDZ0Eeent/bv7SdNx6k2hkmvSewLmy3yz4CL\npEiy35UK6QKBgBsOnclgNPuJCeTbZG/A3+oO6eAEaz3rvkoH+CpNlRGQ3hSlVTct\nRReGRYU7kw6FZVHt1rZn7mFjd6HpdFBHA3v+gzdqVJhaA8Mbj0/LXyzF+t1kgPp2\nAB+Grp+/L9icy4ExSDNqnIXv+Awj47JJqLDy37muf2B7QzbCvqcE5XCRAoGAQz7A\nbYO6mKBxSGUMV0J7wiFSZpaiuYiconmgfTLEHMHfpeEJkpw+8JLAhv8/zlLaPs2J\nrqe3n3wNbv424kVI2KyCuUHxyFWX9j2uGzv7xDEBCg/I/osuxYzJP3avpuW6QPgU\nH/kf9NspN/sBcohbw01du5KhOPB+odVIj7tMRqkCgYEAy0r8jdCJJlGpnrqFV94R\n1yrfzSNRlRjI8/GXqv0LJIuY97plkcx8TWYcFUKPTkkFHUT/HJ9g6LBXs3Um5kPl\nfWCCts9wnhE6pTF7laEnR5kFQ2znZZ6uCV7CghwP8t/fpqBZHGV4XNWdQSXcTp4Q\n9CibNnKnIPiTsRjl2tcYiJo=\n-----END PRIVATE KEY-----\n",
    "client_email": "firebase-adminsdk-ci32b@codeutsava-48425.iam.gserviceaccount.com",
    "client_id": "102822201963495100270",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-ci32b%40codeutsava-48425.iam.gserviceaccount.com"
}
import firebase_admin
from firebase_admin import credentials
from firebase_admin import  firestore
cred = credentials.Certificate(private_key)
firebase_admin.initialize_app(cred)
MY_DB = firestore.client()



# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'background_task',
    'main',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # <-- And here
    ],
}

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')#server side
MEDIA_URL = '/media/'#client side
LOGOUT_REDIRECT_URL = '/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
BACKGROUND_TASK_RUN_ASYNC = True

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'proj.settings')

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['*']