# Generated by Django 2.2.14 on 2022-02-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('hit_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('ecg', models.IntegerField(default=0)),
                ('accelorometer_x', models.IntegerField(default=0)),
                ('accelorometer_y', models.IntegerField(default=0)),
                ('accelorometer_z', models.IntegerField(default=0)),
                ('reading_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesnor_reading_reverse', to='main.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('sensor_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_linked_reverse', to='main.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='DepressionReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depression_index', models.FloatField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('depression_reading_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depression_reading_reverse', to='main.Sensor')),
            ],
        ),
    ]
