# Generated by Django 2.2.14 on 2022-02-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='sensor_linked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_linked_reverse', to='main.Sensor'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='reading_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_reading_reverse', to='main.Sensor'),
        ),
    ]
