# Generated by Django 2.2.14 on 2022-02-26 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20220226_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='user_linked',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended_reverse', to=settings.AUTH_USER_MODEL),
        ),
    ]
