# Generated by Django 2.2.14 on 2022-02-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_extendeduser_user_linked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='user_linked',
            new_name='linked_user',
        ),
    ]
