# Generated by Django 2.2.14 on 2022-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220226_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
