# Generated by Django 2.2.14 on 2022-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sensor_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
