# Generated by Django 2.2.14 on 2022-02-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220226_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
