# Generated by Django 2.2.14 on 2022-02-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sensor_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='depressionreading',
            name='stress_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
