# Generated by Django 2.2.14 on 2022-02-26 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220226_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='sensor_linked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensor_linked_reverse', to='main.Sensor'),
        ),
    ]
