# Generated by Django 2.2.14 on 2022-02-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220226_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='key',
            field=models.CharField(max_length=100),
        ),
    ]
